name: Format and lint

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  stylua:
    name: Format check (StyLua)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Lua formatting
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ tests/

  luacheck:
    name: Static analysis (Luacheck)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: lua/ tests/

  selene:
    name: Lint check (Selene)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Selene linter
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style=quiet lua/ tests/

  lint-summary:
    name: Lint Summary
    runs-on: ubuntu-latest
    needs: [stylua, luacheck, selene]
    if: always()
    steps:
      - name: Check lint results
        run: |
          if [[ "${{ needs.stylua.result }}" == "failure" || "${{ needs.luacheck.result }}" == "failure" || "${{ needs.selene.result }}" == "failure" ]]; then
            echo "❌ Some lint checks failed"
            exit 1
          fi
          echo "✅ All lint checks passed"
