name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write # Required for creating releases
  issues: write   # Required for semantic-release to comment on issues
  pull-requests: write # Required for semantic-release to comment on PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify semantic-release configuration
        run: |
          if [ ! -f .releaserc ] && [ ! -f .releaserc.json ] && [ ! -f .releaserc.js ] && ! grep -q '"release"' package.json; then
            echo "❌ No semantic-release configuration found"
            exit 1
          else
            echo "✅ Semantic-release configuration found"
          fi

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
        # run: npx semantic-release
