# Credits to mason.nvim

name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Generate release notes using release-please
      - id: notes
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          skip-github-release: true

      # Create the GitHub Release using the release note as body
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
